#!/usr/bin/env python
#
# Copyright 2010 Facebook
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import sys
import fbproxy.launcher
import os.path
import logging

def main():
    if len(sys.argv) < 2:
        config_file = 'config.txt'
    else:
        config_file = sys.argv[1]
    if not os.path.isfile(config_file):
        print "usage: main.py configfile"
        print "fbproxy: Cannot find configuration file " + config_file
        return 1
    logging.basicConfig(level=logging.INFO)
    fbproxy.launcher.launch(config_file)

if __name__ == "__main__":
    main()
